name: Terraform Automation with Azure Token

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Login to Azure using Service Principal
      run: |
        az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get Azure Access Token
      id: azure_token
      run: |
        TOKEN=$(az account get-access-token --resource https://management.azure.com/ --query "accessToken" -o tsv)
        echo "::set-output name=azure_token::$TOKEN"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Plan
      env:
        ARM_ACCESS_KEY: ${{ steps.azure_token.outputs.azure_token }}
      run: terraform apply -auto-approve
