name: Terraform Apply

on:
  push:
    branches:
      - main  # Jab bhi aap main branch pe push karenge, yeh trigger hoga.

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.4.5'  # Terraform version set karein

      # Step 3: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secrets se AWS credentials
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "us-east-1"  # Aapke AWS region ke according set karein

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Run Terraform plan
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Apply Terraform configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve
