name: Terraform Automation for AWS Hello World Website

on:
  push:
    branches:
      - main  # This will trigger the action when you push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Set your required version of Terraform

    # Step 3: Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secrets for AWS Access Key
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # GitHub Secrets for AWS Secret Access Key
        aws_region: "us-east-1"  # Region where your resources will be deployed

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Plan Terraform Deployment
    - name: Terraform Plan
      run: terraform plan

    # Step 6: Apply Terraform Plan (Deploy Resources)
    - name: Terraform Apply
      run: terraform apply -auto-approve
