name: Terraform Automation for AWS Hello World Website

on:
  push:
    branches:
      - main  # Ye trigger karega jab aap main branch pe changes push karenge

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Aap apne required version ke according set kar sakte hain

    # Step 3: Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secrets se AWS Access Key ID
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # GitHub Secrets se AWS Secret Access Key
        aws_region: "us-east-1"  # Aap apne region ko change kar sakte hain

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Plan Terraform Deployment
    - name: Terraform Plan
      run: terraform plan

    # Step 6: Apply Terraform Plan (Deploy Resources)
    - name: Terraform Apply
      run: terraform apply -auto-approve

